### PR TITLE
Add edit parameters page

### PR DESCRIPTION
**Pull request by hdoupe**
Allow user to edit parameters after running a simulation:

screen shot 2019-01-02 at 5 13 37 pm

screen shot 2019-01-02 at 5 13 59 pm

### CODE REVIEW

**Comment by hdoupe** [comment]
Todo:

- [ ] add tests for edit page
- [ ] update template engine
- [ ] refactor common code from regular inputs and edit inputs view classes into a mixin class
- [ ] split css into different files (base, forms, outputs, etc)


@MattHJensen do you have any thoughts on the text box shading, the button placement, or general UI in the screenshots above?

**Comment by MattHJensen** [comment]
- The shading will make more sense once the default values are listed below.

**Comment by MattHJensen** [comment]
- Looks like the expansion pluses are showing plus in the expanded state, whereas they should show minus in the expanded state.

**Comment by MattHJensen** [comment]
- [ ] The two "pitch type" labels on two separate lines still look buggy to someone who doesn't know how pandas works. Maybe this is a "hard" UI improvement that should be dealt with later though.

**Comment by MattHJensen** [comment]
Let me think more about the shading, text boxes, underlines. 

- [ ] A good first step would be to make them bolder, and that might make it easier to see what if anything else should be done.

**Comment by MattHJensen** [comment]
- [ ] It seems more natural to me for the download results and edit inputs to be light gray, the same color as the unselected table option or the info buttons.

**Comment by MattHJensen** [comment]
- [ ] nit (as if the above aren't): makes more sense to me to have edit parameters button on top and download results button below it, since the parameter changes are displayed above and results below.

**Comment by hdoupe** [comment]
@MattHJensen thanks for the feedback. I can make several of these changes pretty quickly. 

> A good first step would be to make them bolder, and that might make it easier to see what if anything else should be done.

Can you clarify what should be bolder?

> The two "pitch type" labels on two separate lines still look buggy to someone who doesn't know how pandas works. Maybe this is a "hard" UI improvement that should be dealt with later though.

Let's put this in with the other UI improvements.

> Looks like the expansion pluses are showing plus in the expanded state, whereas they should show minus in the expanded state.

Hmm, good point. I think this should also go with the UI fixes.

**Comment by hdoupe** [comment]
Swapped order and changed color:

screen shot 2019-01-03 at 11 13 42 am

**Comment by hdoupe** [comment]
@MattHJensen I removed the light border that goes around each section and tried the two black/grey shades for the section underline border:

screen shot 2019-01-03 at 1 14 53 pm

screen shot 2019-01-03 at 1 15 14 pm

I'm leaning towards using the lighter color. The section and sub-section widths don't line up right now. The darker border kind of accentuates that. What do you think?

**Comment by MattHJensen** [comment]
I don't mind the light gray for now.

**Comment by hdoupe** [comment]
I do like making the buttons, especially the "go"-type buttons (e.g. run sim), green. I'm starting to feel like the black-grey theme is getting stretched thin.

**Comment by hdoupe** [comment]
Is this close to what you're thinking?

screen shot 2019-01-03 at 3 46 26 pm

**Comment by MattHJensen** [comment]
Also, a few text change suggestions: 
"Reset Parameters" -> "Reset"
"Matchup Parameter Sections" -> "Matchups"
"Run Simulation" -> "Run"

Add "Meta " to the side bar.

**Comment by MattHJensen** [comment]
I like that green, but might be better with bold white lettering.

**Comment by MattHJensen** [comment]
Might even consider changing "Meta-Parameters" to "Parameters."

**Comment by MattHJensen** [comment]
"Matchup Parameter Sections" -> "Matchups"
or "Matchup"

**Comment by hdoupe** [comment]
Alright, here's the new look. The buttons look a little tacky with all of the colors. However, I'm going to wrap up the edit parameter functionality today. Then we can spend tomorrow getting the UI dialed in. Are you alright with pushing some of these things until tomorrow?

screen shot 2019-01-03 at 4 01 47 pm

**Comment by hdoupe** [comment]
Awesome. I'm excited. COMP will be a nice and shiny by the end of the day.

**Comment by hdoupe** [comment]
Merging #38. @MattHJensen thanks for your feedback on this.

**Pull request merged**
