### PR TITLE
Job time reporting

### PR DESCRIPTION
**Pull request by hdoupe**
This PR establishes an approach to reporting the run time and cost of simulations.

The cost is modeled with a Stripe metered plan named `Public Access` where the cost per unit of use is  $0.01. This allows us to apply the same plan to all public projects even though their cost per time unit may vary. For example, if a project uses a server that costs $0.05/sec* and a user runs a simulation that takes 5 seconds, then the reported usage amount is 25 units which corresponds to a $0.25 run cost.

\* This price is made up. See the [AWS Fargate pricing page](https://aws.amazon.com/fargate/pricing/) for more realistic pricing

Approach:
- the run time of each task is recorded by the worker nodes. this data is sent back to the webapp along with the simulation results.
- the cost of the server is set in the `billing.json` file. this cost is stored in the `server_cost` field on the `Project` object
- the webapp sums up the task run times and saves them in the `run_time` field on the `CoreRun` model instance. the total cost of the run is calculated as `run_time * project.server_cost` and is saved in the `run_cost` field on the `CoreRun` model instance

Next steps:
- push the usage amount to Stripe
- add some type of profile page so that users can view their model runs and run costs for a given payment period

An alternative approach to this one is to have a metered plan for each public project. When a user signs up, they are subscribed to each of these plans. When they do a simulation, the run time is reported to stripe for the subscription item corresponding to the project used to run the simulation. This approach may give us some more flexibility but seems like it adds unneeded complexity.

@MattHJensen what do you think of the "Public Access" approach versus the "Metered Plan for each project" approach? Can you see the either one of them handcuffing us in any way?

### CODE REVIEW

**Comment by MattHJensen** [comment]
@hdoupe, I can not think of any significant benefits of the "Metered Plan for each project" approach, but it could be that I am not thinking far enough ahead or am misunderstanding the pros/cons. 

To check my understanding: 

Users will probably want reporting on how much they spent on each simulation and how much they spent on each models. Is it true that we can report how much they spent on a particular model fairly readily with the "Public Access" approach?

Second: I don't think we want to do this, but just checking my understanding: is it true that if we wanted to allow projects to set a per run price that is added to the compute cost, it would be better to go with the "metered plan for each project approach"? E.g., a model costs compute + $X/simulation.

**Comment by hdoupe** [comment]
> Users will probably want reporting on how much they spent on each simulation and how much they spent on each models. Is it true that we can report how much they spent on a particular model fairly readily with the "Public Access" approach?

Yes this is true. However, one of the nice things about going with the metered plan for each project approach is that they will get an email with an invoice breaking down the cost per project, no custom work on our end needed. Further, keeping things separated out like this should make it easier for us to display a page with a user's costs on a per project basis.

> Second: I don't think we want to do this, but just checking my understanding: is it true that if we wanted to allow projects to set a per run price that is added to the compute cost, it would be better to go with the "metered plan for each project approach"? E.g., a model costs compute + $X/simulation.

Well not exactly. If we wanted to add a $X/simulation subscription, then the "quantity" is different. For the current simulation subscription, the cost scales with how much time the simulation takes. For the $X/simulation option, it scales with the number of simulations run. I think the upside with doing the metered run per project approach is that we'd already have a framework for custom, model-specific plans. This should give us more space to be creative in the future (if we want to). If we tried to implement the $X/sim option on top of the public access plan, then I think things could get messy. We would have to implement the new payment rules with our own code instead of working within the stripe framework. 

The public access approach seems simple right now, but I think it would be difficult to build off of in the future. It's a bit like we are fighting the Stripe framework by implementing our own custom metered plans on top of theirs. The metered plan for each approach is very much in line with their framework. Hopefully this should make it easy to work with and extend if need be in the future.

So I'm in favor of going with the "metered plan for each project approach." 

@MattHJensen does this make sense to you?

**Comment by hdoupe** [comment]
The most recent commits:
- implement "metered plan per project approach"
- record run time, calculate price of run given run time and server costs
- report this "price" to Stripe

**Comment by hdoupe** [comment]
The way that Stripe metered plans work is you set a price per unit of quantity usage (compute time in our case). Then, when a subscriber uses the service, the usage is reported to Stripe via a `UsageRecord`. Stipe requires that [quantity](https://stripe.com/docs/api#usage_record_object) and [price(/"amount" in Stipe lingo)](https://stripe.com/docs/api#create_plan) are positive integers or zero. 

Our goal is to charge at compute usage in seconds and server cost in seconds. Ideally, we would be able to set the plan amount at server cost/second and simply report run time in seconds to Stripe. However, server time in seconds tends to be very small. A normally sized AWS server costs around $0.10/hr which works at to  $0.00003/second. 

One way to work around this is:
- set price(/"amount"): one penny, quantity: (run time) / (number of seconds for run to cost a penny)
- find how many seconds a run must be to cost exactly $0.01
- divide run time by that number of seconds to get the number of pennies it would cost, then scale by 100 to get the cost in dollars of the run.
- set a minimum run cost at 1 penny
  - conceivably, run costs could be accounted for on a rolling basis and reported when they cross the penny threshold. however, this could become complicated. thus, my preference is to keep things simple and set a minimum run cost at a penny, for now.

For example, consider a run time of 400 seconds on a server that costs $0.10 an hour.

- run time to cost a penny: 0.01 / (0.10 / 3600)= 360 seconds [3600=num secs in an hour]
- cost of run in pennies: 400 / 360 = 1.1
- scale by 100, round to two places: $0.01

Report run cost at 1 penny, and thus "quantity" of one unit

If run time was 800 seconds, run cost is 2 pennies and "quantity" is two units.

Consider, a run time of 300 seconds:
- cost of run in pennies: 300 / 360 = 0.8
- scale by 100, round to two places: $0.00
- set minimum of a penny: max(0, 0.01) = 0.01

Report run cost at 1 penny, and thus "quantity" of one unit

I'm interested in hearing other approaches to this problem. It's a little annoying that we have to use custom logic around the Stripe API to do this reporting, but I'm having trouble thinking of a better way to work around this problem.

**Comment by MattHJensen** [comment]
My instinct is that users would feel significantly safer knowing the price for a simulation before they run it. The only way I can think to achieve this is with some sort of max_price and rebate approach. 

max_price = max_time * cost_per_time
Where:
- the projects give max_time for every API call or category of API call. 
- floor(max_price) = $0.01

rebate = max_price - actual_price
Where:
- actual_price =actual_time*cost_per_time
- floor(rebate) = $0.01

At the end of the month, we sum the rebates and subtract them from usage. 

We would need to ask the model contributor for a max time by api call. If it hits the max time, we shut down the run and rebate the user. If that happens X times, we take down the model, require it to add additional testing, require it to pay for rebates, or something; we are out some dinero.

Is this additional complexity in billing compared to what you are outlining?

**Comment by MattHJensen** [comment]
The approach I outline above would be particularly difficult in cases where projects allow for custom data uploads. In those cases, the project would need to have some way to estimate max time programmatically based off of data characteristics. That might be tough.

**Comment by MattHJensen** [comment]
After thinking about this overnight, I am leaning back towards the initial proposal to charge directly by time. 

- It may be quite difficult for projects to accurately estimate a max_time accurately, especially since they'll need to estimate max_time for our machines, not their own. 
- It will be difficult to estimate a max_time accurately when users apply the algorithms to their own data. 
- Our unit costs will be hard to predict if we are paying for run-overs. 
- Both users and modelers might be unhappy if we take down models because their time forecasting is poor. 

We may want to add the explicit price (or explicit max_price) capability later as a feature, but I am inclined to stick with time-based pricing in the first version. 

I will go back to considering the questions posed in the [initial question](https://github.com/comp-org/comp/pull/2#issuecomment-424412865).

**Comment by hdoupe** [comment]
Merging #2 even though the price calculation methods are still up for debate. While we are discussing those methods, I want to begin work on a profile page which depends on #2 and #12  (which depends on #2).

**Pull request merged**
